# Generated by Django 3.1.2 on 2020-10-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20201026_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy'), ('BONUS', 'Add bonus points'), ('SELL', 'Sell drink')], max_length=5),
        ),
        migrations.AlterField(
            model_name='log',
            name='card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.card'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.user'),
        ),
    ]
